### PR TITLE
Add GitHub Workflow to check devDependencies

### PR DESCRIPTION
**Pull request by blinkdog**
This PR adds some GitHub Workflows to run checks:
- Are the `devDependencies` defined in `package.json` at the latest versions?
- Does the project build successfully with `make all`?

I'm not sure why GitHub isn't running it on this pull request, but it does work with a PR on my own fork?

https://github.com/blinkdog/rot.js/pull/1

Note this just GitHub automatically running some checks for us when commits are pushed.
It may alert you to reasons that you may not want to merge a PR, but it doesn't modify your ability to do so.

### CODE REVIEW

**Comment by blinkdog** [comment]
@ondras Anything you'd like me to change in this PR?

**Comment by ondras** [comment]
@blinkdog hey, thanks! Finally a good reason for me to read about GitHub Workflows/Actions to understand that :-)

**Comment by ondras** [comment]
@blinkdog I gave it some preliminary look. I am somewhat puzzled by the `build` workflow - what happens with the generated artifacts? Are those stored somewhere? Commited?

**Comment by blinkdog** [comment]
> @blinkdog I gave it some preliminary look. I am somewhat puzzled by the `build` workflow - what happens with the generated artifacts? Are those stored somewhere? Commited?

No, the build artifacts are just discarded with the workflow runner (VM / container).

It's possible to write actions that do automatic releases; they could build `rot.js` and `rot.min.js` and check them into the repo, tag the commit, make an [official release on GitHub](https://github.com/ondras/rot.js/releases), make an [official release on npm](https://www.npmjs.com/package/rot-js?activeTab=versions), etc.

The action I've provided is a bit more modest. It simply runs `make all` and shows green/success if the build succeeds and red/failed if the build fails.

You can still merge a PR with a failing build, although I would ask the author fix the build first. :smile:

**Comment by ondras** [comment]
@blinkdog I gave it some preliminary look. I am somewhat puzzled by the `build` workflow - what happens with the generated artifacts? Are those stored somewhere? Commited?

> It simply runs `make all` and shows green/success if the build succeeds and red/failed if the build fails.

I see, well, this is definitely better than nothing! Going to merge, thanks a lot.

**Pull request merged**
