### PR TITLE
added support for tile colours

### PR DESCRIPTION
**Pull request by TellurionGames**
This uses globalCompositeOperation to allow foreground/background colours on tile displays. I'm using this to render bitmap fonts. It works with draw & drawtext. To render the image without colours, set both foreground and background to 'transparent'.

### CODE REVIEW

**Comment by ondras** [comment]
1. This is terribly inefficient, creating a new HTML Canvas for every tile drawn. I would suggest maintaining one permanent `bufferCanvas` (created in constructor, size adjusted in `.compute`) and re-using it.

1. Do I understand correctly that this change is backwards-incompatible, i.e. breaking existing tile designs by coloring them with default fg/bg colors?

1. Calling `restore()` looks weird without any previous `save()`

1. Would you be so kind to add an example to the interactive manual? I am having hard times understanding how exactly does this work myself.

**Comment by TellurionGames** [comment]
Thanks for the great feedback!

1. I've added the optimization you suggested. Thanks for pointing that out.
2. I added an option to enable tile colouring. This is off by default, so this maintains backwards-compatibility.
3. My mistake. Fixed.
4. I added a quick example to the manual.

**Comment by ondras** [comment]
Thanks for the changes! I will merge this.

I plan, however, on implementing some minor changes afterwards (changing the option name to `tileColorize` and moving the secondary buffer to the tile backend), so please make sure to update your version accordingly.

**Comment by ondras** [comment]
Done, please check the code. I also changed your globalCompositeOperation for background drawing to "destination-over", as it works better with RGBA values. Please confirm that this still works as expected in your use case.

**Pull request merged**
