### PR TITLE
updated to support AMD or CJS loaders

### PR DESCRIPTION
**Pull request by erikyuzwa**
* Updated `Makefile` to create a version of the library that supports AMD or CommonJS loaders

### CODE REVIEW

**Comment by erikyuzwa** [comment]
Really wasn't sure if this was wanted, or where you'd want to put the `pre` and `post` files. Definitely open to any suggestions.

**Comment by ondras** [comment]
Not exactly wanted, but brings no overhead => whatever, I guess. Why not.

I would put {pre,post}.txt into a dedicated directory (`umd`?), as the root directory is getting too cluttered with metadata. Also, updating the `rot.js` (and `rot.min.js`) files with the improved bundle would be nice.

**Comment by erikyuzwa** [comment]
Not a problem at all, thus updated.

**Comment by OldrichKruchna** [comment]
Seems both files were moved into umd folder and also bundles were updated. Could it be reviewed again?

**Comment by ondras** [comment]
Sorry, I somehow completely missed this update. Thanks for the fix!

**Comment by erikyuzwa** [comment]
no problem at all - I had kinda forgotten about this one too. Thanks so much! :bow:

**Comment by ondras** [comment]
Looks like this change somehow broke the node.js build: https://github.com/ondras/rot.js/issues/124

**Comment by erikyuzwa** [comment]
ugh! not good. I'll take a look @ondras

**Comment by ondras** [comment]
I *hope* I already fixed that (see node build of rot.js v0.6.4) :-)

**Pull request merged**
