### PR TITLE
Fix dividedmaze

### PR DESCRIPTION
**Pull request by kosinaz**
The DividedMaze generator algorithm allowed holes on the walls on odd coordinates, and that prevented additional wall building on both sides of that hole, resulting in mazes with some 3-wide corridors.

As a simple fix, I have added an extra check for each of the four walls to only store their even coordinates in the list of potential hole coordinates.

### CODE REVIEW

**Comment by kosinaz** [comment]
See the before and after example.
current
fixed

**Comment by ondras** [comment]
Great, thanks!

**Comment by kosinaz** [comment]
Sorry, I haver accidentally added the two images as well. Feel free to delete them.

Also, see my related comment in #76 about my further plans on DividedMaze. I'm happy to contribute if you think they are matching with your intentions.

**Comment by ondras** [comment]
> Also, see my related comment in #76 about my further plans on DividedMaze. I'm happy to contribute if you think they are matching with your intentions.

Why not! If you manage to maintain API compatibility and set those options to defaults that provide the current implementation...

**Pull request merged**
