### PR TITLE
Fixed destructiveness of Array.prototype.randomize()

### PR DESCRIPTION
**Pull request by jakofranko**
Hi there @ondras ! Fixed the problem where using `.randomize()` on an array destroyed the array's value. I'm not sure if I need to compile rot.js as well? Let me know if you need me to tweak anything or if you think this will cause any problems...

By the way, thank you so much for this tool! I have stumbled across roguelikes within the last few years, and as a web developer I was thrilled to find such a useful framework that uses my 'bread and butter' language: Javascript!

### CODE REVIEW

**Comment by ondras** [comment]
Hi @jakofranko,

thanks for your code and sorry for my late reply (just returned from vacation).

As far as the cloning goes, you can prehaps simplify the whole operation to 
```js
var clone = this.slice();
```
?

**Comment by jakofranko** [comment]
Good idea, I didn't realize you could use slice to make shallow copies like that. Handy! I'll update and re-push.

**Comment by ondras** [comment]
Cool, thanks!

**Comment by jakofranko** [comment]
Thanks for the framework! Glad I could contribute.

**Pull request merged**
