### PR TITLE
Homepage Link Repair

### PR DESCRIPTION
**Pull request by gledos**
Edit HomePage Link in README.md

Remoce missing Scripts page on the homepage.

```
- Tests
```

### CODE REVIEW

**Comment by ondras** [comment]
Hi @gledos,

thanks for the PR. Let me check those `Tests`, if I can fix them - it would be nice to have them.

**Comment by gledos** [comment]
thanks

**Comment by ondras** [comment]
Tests should work again (https://ondras.github.io/rot.js/tests/). Please, @gledos, sync with the current master and I will then merge this PR.

**Comment by gledos** [comment]
Thank you for fixing this feature, then I'll close this PR.

**Pull request closed without merging**
